### ISSUE TITLE
update contributing and releases guide

### ISSUE THREAD

**Issue by hansvancalster** [inbo/protocolsource#56]
The contributing guide will need to be updated when protocolhelper v0.3.0 is released:

- [ ] explain GHAs which check structure and frontmatter of protocols 
- [ ] mention `update_version_number()`
- [ ] update code examples (especially with regard to how author names should be passed and version number = get_version_number())

Idem for the RELEASES.md file:

- [ ] most or all of the steps will be automated

**Comment by Eveltjen00** [comment]
**contributing guide: Setup your local repository**
- [ ] go to the [protocols repository](https://github.com/inbo/protocols/) and press the Clone button => go to the [protocols repository](https://github.com/inbo/protocols/) and press the green "Code" button.
- [ ] copy the URL to the clipboard => copy the HTTPS URL to the clipboard
- [ ] protocols will be automatically suggested as project directory name (keep it that way) => protocolsource will be automatically suggested as project directory name (keep it that way)
- [ ] In the field Create project as subdirectory of select a folder on your local disc (do not use a folder that google drive file stream synchronizes). For instance C:/R/repositories. => it is not a 100% clear if the example C:/R/repositories is what you should use; or what you shouldn't use. I'm assuming the first. => Restructure sentence: In the field Create project as subdirectory of select a folder on your local disc. For instance C:/R/repositories. Do not use a folder that google drive file stream synchronizes.
- [ ] Click OK => Click "Create project"

**Comment by Eveltjen00** [comment]
**contributing guide**
- [ ]  between setup your local repository and workflow, link to how to install protocolhelper in R

**Comment by ElsLommelen** [comment]
> * In the field Create project as subdirectory of select a folder on your local disc (do not use a folder that google drive file stream synchronizes). For instance C:/R/repositories. => it is not a 100% clear if the example C:/R/repositories is what you should use; or what you shouldn't use. I'm assuming the first. => Restructure sentence: In the field Create project as subdirectory of select a folder on your local disc. For instance C:/R/repositories. Do not use a folder that google drive file stream synchronizes.

I wonder if this is still a problem.  First of all: is google drive file stream still used at INBO?  For some months I have a new laptop with the recent google syncing software (not sure of the exact name, the program is called 'Google Drive'), and this seems not to give any problems with a (bookdown) repository that I saved in a folder synced with google drive.  (I used to have insync on my previous laptop to avoid syncing related problems, but now I'm giving it a try without, and it seems to work fine with the regular google drive installation we have now.)  So if the old google drive file stream that caused problems, is not used anymore at INBO, it might not be necessary anymore to keep adding this warning.

(I even ceased to save scripts and documents directly under C:/R to not create a mess everywhere on my computer, so I would rather leave it up to the user where to save it if there is no reason to save it on a specific place.)

> **contributing guide: Setup your local repository**

And a more general remark: since one year one needs an additional authentication step to be able to push local changes (create a GitHub token or use ssh, see [this tutorial](https://inbo.github.io/tutorials/tutorials/git_authentication/#using-the-https-protocol)), so this setup is a bit more complicated as explained above for someone that uses GitHub for the first time.  Personally I think it would be better to refer to a (INBO) manual on how to clone a repository (and put some effort in that manual), rather than adding the same manual to all repositories and trying to keep it up-to-date everywhere.  As security measures tend to change often, this maintenance of a manual on every single repository is likely to be a huge effort the long term, and forgetting to do so, has a large influence on users.

(For advanced GitHub users, on the other hand, it is less motivating to struggle through a long manual that contains too much information that they know already (e.g. cloning a repo), and they risk to miss one step if several steps are spread out over multiple steps.)

So I would rather not overload the manual with 'general steps' that are explained elsewhere, but rather refer to other manuals to keep the manual short and uncluttered

**Comment by ElsLommelen** [comment]
> **contributing guide**
> 
> * [ ]   between setup your local repository and workflow, link to how to install protocolhelper in R

@Eveltjen00 If you are reviewing the manual, I think it would be better if you would use branch renv-setup (which is the most recent develop branch).  We are working on a new version of protocolsource, which will do a lot of stuff automatically.  Among others, protocolsource will use renv, by which protocolhelper should be installed automatically in your local protocolsource project after opening it (only to be used in project protocolsource).  So in the near future, it will not be necessary anymore for users of protocolsource to install protocolhelper (so no need to add this to the manual in the next version).

**Comment by ElsLommelen** [comment]
@Eveltjen00 I happend to pass the [contributing guidelines](https://github.com/inbo/protocolsource/blob/main/CONTRIBUTING.md), and I noticed most of the to do's that you added above, seem to be steps that are mentioned in these guidelines.  So I'm not sure why you added this here?  I'll leave it up to @hansvancalster to have a look at it after his holidays (I'm only doing some automation stuff and I don't know the user site very well), but maybe it could be useful to already clarify this a bit for him?

**Comment by hansvancalster** [comment]
Thanks for reviewing the contributing guidelines. I think all of your concerns are now addressed. See [contributing guidelines in renv-setup branch](https://github.com/inbo/protocolsource/blob/renv-setup/CONTRIBUTING.md)
